name: 'PHP AUDIT ACTION'
description: 'GitHub Actions for PHP LIbrary Secrity Checker'
author: 'glassmonkey'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WORK_DIR: ${{ inputs.WORK_DIR }}
    ISSUE_LABELS: ${{ inputs.ISSUE_LABELS }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  WORK_DIR:
    description: Relative path of the directory where composer.lock exists
    required: false
    default: ""
  ISSUE_LABELS:
    description: Apply labels to a issue. e.g bugs,invalid
    required: false
    default: ""
