version: '3.4'

services:
  app:
    build:
      target: run
      context: .
    image: glassmonenkey/actions-php-audit
    environment:
      WORK_DIR: /app
    working_dir: /app
  script:
    build:
      target: build
      context: .
    image: glassmonenkey/actions-php-audit-script
    volumes:
      - ./script:/go/src/app