name: Alert Composer Audit
on:
  push:
    branches:
      - master
jobs:
  check-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: glassmonkey/actions-php-audit@v1
        name: php-audit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          ISSUE_LABELS: bugs